<?php
include_once 'GameEngine/Generator.php';
$preview = isset($_GET['preview']) && $_GET['preview'] === '1';
if (!$preview) include_once 'GameEngine/Village.php';
include_once 'GameEngine/ActivityRewards.php';

$message = '';
if (!$preview && isset($session->uid) && isset($_POST['claim_activity'])) {
    $result = ActivityRewards::claim($session->uid); $message = $result[1];
}
$state = (!$preview && isset($session->uid)) ? ActivityRewards::state($session->uid) : ['available' => true, 'next_claim' => time(), 'total_claims' => 0];
?><!doctype html><html <?php echo function_exists('tz_html_dir_attrs') ? tz_html_dir_attrs() : 'dir="rtl"'; ?>><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Activity reward</title><style>body{font:16px Arial;color:#17324d;background:#f7fafc;margin:0;padding:24px}.activity{max-width:460px;margin:auto;border:1px solid #d7e0e8;border-radius:14px;background:#fff;overflow:hidden;box-shadow:0 8px 24px #17324d18}.head{text-align:center;padding:22px;background:#f2f6fa;border-bottom:1px solid #d7e0e8}h1{margin:0 0 8px;font-size:27px}.body{padding:22px}.timer{margin:12px 0;padding:14px;text-align:center;border:1px solid #f3b6b6;border-radius:14px;color:#bd3030;font:bold 31px monospace}.tasks{margin-top:22px;border:1px solid #e0e7ed;border-radius:12px;padding:12px}.tasks a{display:block;padding:10px 4px;border-bottom:1px solid #e5ebef;color:#47718f;text-decoration:none}.tasks a:last-child{border:0}button{width:100%;padding:12px;border:0;border-radius:8px;background:#39b967;color:#fff;font-weight:bold;cursor:pointer}.message{text-align:center;margin-bottom:12px}</style></head><body><main class="activity"><header class="head"><h1>مكافأة النشاط</h1><div>متاحة كل 6 ساعات</div></header><section class="body"><?php if ($message !== ''): ?><p class="message"><?php echo htmlspecialchars($message, ENT_QUOTES, 'UTF-8'); ?></p><?php endif; ?><div id="timer" class="timer">--:--:--</div><form method="post"><button type="submit" name="claim_activity" value="1">استلام المكافأة</button></form><div class="tasks"><strong>كيف تزيد مكافأتك؟</strong><a href="allianz.php">تفاعل في الدردشة العامة</a><a href="nachrichten.php">أرسل رسائل للاعبين</a><a href="karte.php">هاجم الواحات</a><a href="karte.php">هاجم اللاعبين الآخرين</a></div></section></main><script>var end=<?php echo (int)$state['next_claim']; ?>*1000;function tick(){var n=Math.max(0,Math.floor((end-Date.now())/1000)),h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;document.getElementById('timer').textContent=n===0?'جاهزة الآن':String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');}tick();setInterval(tick,1000);</script></body></html>